### ISSUE TITLE
The bot throws "pyrogram.dispatcher - ERROR" when I try to send a picture to it

### ISSUE THREAD

**Issue by hash070** [Adarsh-Goel/Filestreambot-pro#36]
When I try to send a picture to the bot, it returns nothing, and the program will show the following error log at the same time.

```log
2022-10-22 12:16:59,261 - pyrogram.dispatcher - ERROR - Telegram says: [400 ENTITY_BOUNDS_INVALID] - The message entity bounds are invalid (caused by "messages.SendMessage")
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/usr/local/lib/python3.8/dist-packages/pyromod/listen/listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "/root/filestreambot-pro/Adarsh/bot/plugins/stream.py", line 105, in private_receive_handler
    await m.reply_text(
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/types/messages_and_media/message.py", line 959, in reply_text
    return await self._client.send_message(
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/methods/messages/send_message.py", line 124, in send_message
    r = await self.invoke(
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/methods/advanced/invoke.py", line 77, in invoke
    r = await self.session.invoke(
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/session/session.py", line 361, in invoke
    return await self.send(query, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/session/session.py", line 331, in send
    RPCError.raise_it(result, type(data))
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.EntityBoundsInvalid: Telegram says: [400 ENTITY_BOUNDS_INVALID] - The message entity bounds are invalid (caused by "messages.SendMessage")
```

**Comment by Adarsh-Goel** [comment]
umm seems like your picture has no name!
test it with some other pic.
If issues persists inform me

**Comment by hash070** [comment]
![image](https://user-images.githubusercontent.com/62081013/197337103-0e3458c9-d437-489c-a8a8-b14c70fe7f86.png)
![image](https://user-images.githubusercontent.com/62081013/197337503-365ac611-b35e-456e-9215-922299379459.png)
Will, the first picture is directly pasted from some website, and the second picture is directly dragged from my desktop, which surely has a file name. They both make the bot fail to return a link. 
The third is a normal text file. It succeeded.

**Comment by Adarsh-Goel** [comment]
a fix has been pushed now try please

**Comment by hash070** [comment]
Umm, that's not working.

![image](https://user-images.githubusercontent.com/62081013/197338243-443cb011-7382-4350-8c0e-21bf7159559c.png)
![image](https://user-images.githubusercontent.com/62081013/197338315-bb3b8419-36e5-4cb1-ae15-5f40dff8dd5f.png)

**Comment by Adarsh-Goel** [comment]
is this the latest code??

**Comment by Adarsh-Goel** [comment]
if yes i will consider fixing it later.

**Comment by hash070** [comment]
Of course, I know that u pushed a fix, and I'm using the latest code.
![image](https://user-images.githubusercontent.com/62081013/197339559-838ba30f-56c4-418f-9705-b02b1cadbc51.png)

I still don't know where went wrong. The bot can't return the links directly to the user, but it can return a correct link in `BIN_CHANNEL`...

![image](https://user-images.githubusercontent.com/62081013/197339293-1d0e30d3-7ca9-48eb-bfaa-1841061b9a5f.png)

![image](https://user-images.githubusercontent.com/62081013/197339426-32ea88f8-f443-4060-8bf2-3a1eafc47cbf.png)

**Comment by Adarsh-Goel** [comment]
so its not fixed ?

**Comment by Adarsh-Goel** [comment]
will be fixed soon (4-5 days) exams going on dude 😢

**Comment by hash070** [comment]
> so its not fixed ?

Yes, it's not fixed.

**Comment by hash070** [comment]
> will be fixed soon (4-5 days) exams going on dude 😢

OK, it's just a small bug, the exam is first. I wish you a high score. 😀
